export default function QuizHeader({

  cached

}) {

  return (

<div className="mb-8 text-center sm:text-left">

    <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white">

        🎯 AI Quiz

    </h1>

    {

        cached !== null && (

            <div className="mt-3 inline-flex items-center px-4 py-2 rounded-full bg-gray-100 dark:bg-gray-700">

                <p className="font-semibold text-sm sm:text-base text-gray-700 dark:text-gray-200">

                    {

                        cached

                            ?

                            "📦 Loaded from MongoDB"

                            :

                            "🤖 Generated by Gemini"

                    }

                </p>

            </div>

        )

    }

</div>

);

}