import { useContext, useState, useMemo } from "react";
import { StudyContext } from "../context/StudyContext";
import jsPDF from "jspdf";
import toast from "react-hot-toast";
import SummarySkeleton from "../components/skeletons/SummarySkeleton";

export default function SummaryPage() {

  const {
    summary,
    setSummary,
    title,
    noteId,
    globalSearch,
    setNotifications
  } = useContext(StudyContext);

  const [loading, setLoading] = useState(false);
  const generateSummary = async () => {
    
    if (!noteId) {
      
      toast.error("Please upload a PDF first.");
      
      return;
      
    }
    setLoading(true);

    try {

      setLoading(true);

      const token = localStorage.getItem("token");

      const res = await fetch(
        `${import.meta.env.VITE_API_URL}/api/summary`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`
          },
          body: JSON.stringify({
            noteId
          })
        }
      );

      const data = await res.json();

      console.log("Summary Response:", data);

      if (data.success) {

        setSummary(data.summary);
        setNotifications(prev => [

          {

            id: Date.now(),

            text: "Summary generated successfully 📝",

            time: new Date().toLocaleTimeString()

          },

          ...prev

        ]);

        if (data.cached) {

          console.log("📦 Summary Loaded from MongoDB");

        } else {

          console.log("🤖 Summary Generated by Gemini");

        }

      } else {

        toast.error(data.message || data.error);

      }

    } catch (err) {

      console.error(err);

      toast.error("Summary generation failed.");

    } finally {

      setLoading(false);

    }

  };

  const handleCopy = () => {

    navigator.clipboard.writeText(summary);

    toast.success("Summary copied.");

  };

  const highlightedSummary = useMemo(() => {

    if (!globalSearch.trim()) return summary;

    const regex = new RegExp(`(${globalSearch})`, "gi");

    return summary.split(regex);

  }, [summary, globalSearch]);

  const handleDownload = () => {

    if (!summary) {

      toast.error("No summary available.")

      return;

    }

    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const margin = 15;

    let y = 20;

    // Header

    doc.setFillColor(37, 99, 235);

    doc.rect(0, 0, pageWidth, 28, "F");

    doc.setTextColor(255, 255, 255);

    doc.setFontSize(20);

    doc.setFont("helvetica", "bold");

    doc.text("AI Study Assistant", pageWidth / 2, 18, {

      align: "center"

    });

    y = 40;

    // Title

    doc.setTextColor(0);

    doc.setFontSize(16);

    doc.setFont("helvetica", "bold");

    doc.text(title || "Untitled Note", margin, y);

    y += 10;

    // Date

    doc.setFontSize(11);

    doc.setFont("helvetica", "normal");

    doc.text(

      `Generated: ${new Date().toLocaleString()}`,

      margin,

      y

    );

    y += 15;

    // Heading

    doc.setFontSize(14);

    doc.setFont("helvetica", "bold");

    doc.text("AI Generated Summary", margin, y);

    y += 10;

    doc.setFontSize(12);

    doc.setFont("helvetica", "normal");

    const lines = doc.splitTextToSize(

      summary,

      pageWidth - margin * 2

    );

    lines.forEach(line => {

      if (y > pageHeight - 20) {

        doc.addPage();

        y = 20;

      }

      doc.text(line, margin, y);

      y += 7;

    });

    // Footer

    const totalPages = doc.getNumberOfPages();

    for (let i = 1; i <= totalPages; i++) {

      doc.setPage(i);

      doc.setFontSize(10);

      doc.setTextColor(120);

      doc.text(

        `Page ${i} of ${totalPages}`,

        pageWidth / 2,

        pageHeight - 10,

        {

          align: "center"

        }

      );

    }

    doc.save(`${title || "Summary"}.pdf`);

  };
  const handleDownloadTxt = () => {

    if (!summary) {
      toast.error("No summary available.");
      return;
    }

    const blob = new Blob([summary], { type: "text/plain" });

    const url = window.URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;

    a.download = `${title || "Summary"}.txt`;

    a.click();

    window.URL.revokeObjectURL(url);

  };

  return (

  <div className="min-h-screen bg-gray-100 dark:bg-gray-900 flex justify-center items-start px-4 sm:px-6 lg:px-8 py-6 sm:py-8 transition-all duration-300 overflow-x-hidden">

    <div className="w-full max-w-4xl bg-white dark:bg-gray-800 shadow-2xl rounded-2xl border border-gray-200 dark:border-gray-700 p-5 sm:p-8 transition-all duration-300">

      <button
        onClick={generateSummary}
        disabled={loading}
        className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700 hover:scale-105 active:scale-95 transition-all duration-300 text-white px-6 py-3 rounded-xl shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
      >

        {
          loading
            ? "⏳ Generating..."
            : "✨ Generate Summary"
        }

      </button>

      {

        loading ?

          <div className="mt-8">

            <SummarySkeleton />

          </div>

          :

          summary ?

            <>

              <h2 className="mt-8 text-2xl sm:text-3xl font-bold text-gray-800 dark:text-white break-words">

                📚 {title}

              </h2>

              <div className="mt-6 bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-xl p-5 sm:p-6 text-gray-700 dark:text-gray-200 whitespace-pre-wrap break-words leading-7 sm:leading-8">

                {

                  Array.isArray(highlightedSummary)

                    ?

                    highlightedSummary.map((part, index) =>

                      part.toLowerCase() === globalSearch.toLowerCase()

                        ?

                        <mark
                          key={index}
                          className="bg-yellow-300 text-black px-1 rounded"
                        >

                          {part}

                        </mark>

                        :

                        <span key={index}>

                          {part}

                        </span>

                    )

                    :

                    highlightedSummary

                }

              </div>

              <div className="mt-8 flex flex-col sm:flex-row flex-wrap gap-4">

                <button
                  onClick={handleCopy}
                  className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700 hover:scale-105 active:scale-95 transition-all duration-300 text-white px-6 py-3 rounded-xl shadow-lg"
                >

                  📋 Copy

                </button>

                <button
                  onClick={handleDownload}
                  className="w-full sm:w-auto bg-green-600 hover:bg-green-700 hover:scale-105 active:scale-95 transition-all duration-300 text-white px-6 py-3 rounded-xl shadow-lg"
                >

                  📄 Download PDF

                </button>

                <button
                  onClick={handleDownloadTxt}
                  className="w-full sm:w-auto bg-purple-600 hover:bg-purple-700 hover:scale-105 active:scale-95 transition-all duration-300 text-white px-6 py-3 rounded-xl shadow-lg"
                >

                  📄 Download TXT

                </button>

              </div>

            </>

            :

            <div className="flex flex-col items-center justify-center py-16 sm:py-20 text-center">

              <div className="text-6xl sm:text-7xl mb-5">

                📄

              </div>

              <h2 className="text-2xl sm:text-3xl font-bold text-gray-800 dark:text-white">

                No Summary Yet

              </h2>

              <p className="mt-3 text-sm sm:text-base text-gray-500 dark:text-gray-400 max-w-md">

                Upload your notes first, then click
                <span className="font-semibold"> Generate Summary </span>
                to let AI create a concise summary.

              </p>

            </div>

      }

    </div>

  </div>

);

}